### ISSUE TITLE
Multiple FCM Token for a single user

### ISSUE THREAD

**Issue by kdrmlhcn** [avto-dev/firebase-notifications-laravel#12]
How do we handle multiple FCM tokens for a single user?

**Comment by jetexe** [comment]
Hi! Just as any other notification channel in Laravel
For example you can use [on-demand notifications](https://laravel.com/docs/7.x/notifications#on-demand-notifications)

**Comment by jetexe** [comment]
Closed due to inactive. If you have any questions, you are welcome to create an issue
